module.exports = {
  SAVE_TO_STORAGE: 'saveToStorage',
  RESTORE_FROM_STORAGE: 'restoreFromStorage',
  STORAGE_DATA: 'storageData',
  RESET_DATA: 'resetData',
  CHECK_TOKEN: 'checkToken',
  INITIALIZE_STORE: 'initializeStore',
  INITIALIZE_STATUS: 'initializeStatus',
  AFTER_INITIALIZE: 'initialized',
  CHANGE_STATUS: 'changeStatus',
  SET_CURRENT_STATUS: 'setCurrentStatus',
  SET_CURRENT_SSID: 'setCurrentSSID',
  INIT_PREFERENCE: 'initPreference',
  OPEN_PREFERENCE: 'openPreference',
  CLOSE_PREFERENCE: 'closePreference',
  UPDATE_PREFERENCE: 'updatePreference',
  SYNC_STATUS: 'syncStatus',
  CLEAR_STATUS: 'clearStatus',
}
