module.exports = {
  SAVE_TO_STORAGE: 'saveToStorage',
  RESTORE_FROM_STORAGE: 'restoreFromStorage',
  CLEAR_STORAGE: 'resetData',
  STORAGE_DATA: 'storageData',
  INITIALIZE_STORE: 'initializeStore',
  INITIALIZE_STATUS: 'initializeStatus',
  TOKEN_VERIFIED: 'tokenVerified',
  AFTER_INITIALIZE: 'initialized',
  CHANGE_STATUS: 'changeStatus',
  SET_CURRENT_STATUS: 'setCurrentStatus',
  SET_CURRENT_SSID: 'setCurrentSSID',
  INIT_PREFERENCE: 'initPreference',
  OPEN_PREFERENCE: 'openPreference',
  CLOSE_PREFERENCE: 'closePreference',
  UPDATE_PREFERENCE: 'updatePreference',
  UPDATE_TOKEN: 'updateToken',
  GOT_TOKEN: 'gotToken',
  SET_INFO: 'setInfo',
  OPEN_SIGNIN: 'openSignin',
  SYNC_STATUS: 'syncStatus',
  CLEAR_STATUS: 'clearStatus',
  CHANGE_PREFERENCE_MENU: 'changePreferenceMenu',
  RESTART_APP: 'restartApp',
  EXIT_APP: 'exitApp',
  READY_TO_SHOW: 'readyToShow',
  SET_CUSTOM_EMOJI: 'setCustomEmoji',
  SET_PROFILE_CUSTOM: 'setProfileCustom',
  SUSPENDED: 'suspended',
  RESUMED: 'resumed',

  GET_WEBVIEW_CONTENT: 'getWebviewContent',
  DOM_READY: 'dom-ready',
  DID_NAVIGATE: 'did-navigate',
  IPC_MESSAGE: 'ipc-message',
}
